[package]

name = "acronymy"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
build = "build.rs"

[[bin]]

name = "acronymy"
path = "src/main.rs"

[[bin]]

name = "initdb"
path = "src/initdb.rs"

[dependencies.sqlite3]
git = "https://github.com/linuxfood/rustsqlite.git"

[build-dependencies]
capnpc = "0.0.17"

[dependencies]
capnp = "0.0.16"
capnp-rpc = "0.0.9"
url = "0.2.6"
time = "0.1.3"